import { AuthProvider } from "./Providers";
import "./globals.css";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav /> 
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
